apiVersion: v1
kind: Service
metadata:
  name: traffic-mirror
  namespace: default
spec:
  type: NodePort
  selector:
    app: mirror
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-mirror
  namespace: default
  labels:
    app: mirror
spec:
  selector:
    matchLabels:
      app: mirror
  replicas: 1
  template:
    metadata:
      labels:
        app: mirror
    spec:
      containers:
      - image: daviddetorres/traffic-mirror:latest
        imagePullPolicy: IfNotPresent
        name: traffic-mirror
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-generator
  namespace: default
  labels:
    app: generator
spec:
  selector:
    matchLabels:
      app: generator
  replicas: 1
  template:
    metadata:
      labels:
        app: generator
    spec:
      containers:
      - image: locustio/locust
        imagePullPolicy: IfNotPresent
        name: locust
        env:
        - name: LOCUSTFILE_PATH
          value: "/mnt/locust/traffic-generator.py"
        - name: TARGET_URL
          value: "http://traffic-mirror:8080"
        - name: LOCUST_OPTS
          value: "--no-web -c 10 -r 10"
        volumeMounts:
        - mountPath: /mnt/locust
          name: traffic-generator
      volumes:
      - configMap:
          defaultMode: 420
          name: traffic-generator
        name: traffic-generator
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traffic-generator
  namespace: default
data:
  traffic-generator.py: |
    from locust import Locust, TaskSet, task, between, HttpLocust

    class MyTaskSet(TaskSet):
        headers = {"Host": "traffic-mirror.io"}

        @task(100)
        def NoLatencyLightWeight(self):
            self.client.request("GET","/ok/0/500", 
                                headers=self.headers)

        @task(100)
        def MediumLatencyLightWeight(self):
            self.client.request("GET","/ok/500/500", 
                                headers=self.headers)

        @task(10)
        def HighLatencyLightWeight(self):
            self.client.request("GET","/ok/5000/500", 
                                headers=self.headers)
        
        @task(100)
        def NoLatencyMediumWeight(self):
            self.client.request("GET","/ok/0/50000", 
                                headers=self.headers)
        
        @task(100)
        def MediumLatencyMediumWeight(self):
            self.client.request("GET","/ok/500/50000", 
                                headers=self.headers)
        
        @task(10)
        def HighLatencyMediumWeight(self):
            self.client.request("GET","/ok/5000/50000", 
                                headers=self.headers)

        @task(20)
        def NoLatencyHeavyWeight(self):
            self.client.request("GET","/ok/0/5000000", 
                                headers=self.headers)
        
        @task(20)
        def MediumLatencyHeavyWeight(self):
            self.client.request("GET","/ok/500/5000000", 
                                headers=self.headers)
      
        @task(10)
        def HighLatencyHeavyWeight(self):
            self.client.request("GET","/ok/5000/5000000", 
                                headers=self.headers)
        
        @task(100)
        def LightWeightPost(self):
            self.client.request("POST","/ok/0/0",  
                                data={"data":"0"*500}, 
                                headers=self.headers)
        
        @task(100)
        def MediumWeightPost(self):
            self.client.request("POST","/ok/0/0", 
                                data={"data":"0"*50000}, 
                                headers=self.headers)
        
        @task(20)
        def HeavyWeightPost(self):
            self.client.request("POST","/ok/0/0", 
                                data={"data":"0"*5000000}, 
                                headers=self.headers)
      
        @task(10)
        def Error404(self):
          self.client.request("GET","/error/404", 
                            headers=self.headers)
      
        @task(10)
        def Error403(self):
          self.client.request("GET","/error/403", 
                            headers=self.headers)

        @task(10)
        def Error500(self):
          self.client.request("GET","/error/500", 
                            headers=self.headers)
        
        @task(10)
        def Error503(self):
          self.client.request("GET","/error/503", 
                            headers=self.headers)

    class TrafficMirrorUser(HttpLocust):
        task_set = MyTaskSet    
        wait_time = between(5, 15)